name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (eslint)
        run: npm run lint

      - name: Type check (tsc)
        run: npm run type-check

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload logs (if any)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs
          if-no-files-found: ignore 